# Generated by Django 3.0.3 on 2020-02-26 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='datestamp',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
