# Generated by Django 3.0.3 on 2020-02-26 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0002_auto_20200226_2124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='humidity',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='data',
            name='temperature',
            field=models.FloatField(default=0),
        ),
    ]
